fixtures:
  repositories:
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    staging:
      repo: 'git://github.com/nanliu/puppet-staging.git'
    ibm_installation_manager:
      repo: 'git://github.com/puppetlabs/puppetlabs-ibm_installation_manager.git'
    debug: 'https://github.com/nwops/puppet-debug.git'
  symlinks:
    'websphere_application_server': "#{source_dir}"
